export const technologies = {
  "ant-design": { label: "Ant Design" },
  astro: { label: "Astro" },
  bison: { label: "Bison" },
  c: { label: "C" },
  docker: { label: "Docker" },
  fastapi: { label: "FastAPI" },
  fastify: { label: "Fastify" },
  flex: { label: "Flex" },
  "github-actions": { label: "GitHub Actions" },
  grafana: { label: "Grafana" },
  grpc: { label: "gRPC" },
  javascript: { label: "JavaScript" },
  k6: { label: "k6" },
  mongodb: { label: "MongoDB" },
  nodejs: { label: "Node.js" },
  postgresql: { label: "PostgreSQL" },
  prometheus: { label: "Prometheus" },
  python: { label: "Python" },
  react: { label: "React" },
  "react-bootstrap": { label: "React Bootstrap" },
  "redux-toolkit": { label: "Redux Toolkit" },
  socketio: { label: "Socket.IO" },
  terraform: { label: "Terraform" },
  "testing-library": { label: "Testing Library" },
  typescript: { label: "TypeScript" },
  vitest: { label: "Vitest" },
  "yandex-cloud": { label: "Yandex Cloud" },
  make: { label: "Make" },
  webassembly: { label: "WebAssembly" },
  "tanstack-start": { label: "TanStack Start" },
  "prisma-orm": { label: "Prisma ORM" },
  mantine: { label: "Mantine" },
  paraglide: { label: "Paraglide" },
  playwright: { label: "Playwright" },
  vite: { label: "Vite" },
  cs: { label: "C#" },
  cpp: { label: "C++" },
  firebase: { label: "Firebase" },
  html: { label: "HTML" },
  css: { label: "CSS" },
  sdl2: { label: "SDL2" },
} as const;

export const getTechnology = (id: string) =>
  technologies[id as keyof typeof technologies];
